# -----------------------------------------------------------------------------
# OVERVIEW:  jstandard.properties File
# -----------------------------------------------------------------------------
# The jstandard.properties file specifies the location of the API libraries, the
# name of your application, and other options.  The following two properties are
# required properties that must be defined in the jstandard.properties file:
#
#    * jna.library.path
#      The path to the bin directory in which *.dll/*.so files reside. This is
#      the location of the native API library.
#
#    * jstandard.DBC.program
#      Your application name. This will be provided by IDC. The name must begin
#      with the grave accent (`) and followed by 12 characters or less.
#
# Other options that may be set in the jstandard.properties file include:
#
#    * jstandard.DBC.manualConnect
#    * jstandard.DBC.timeouts.connection
#    * jstandard.DBC.tcp.nodelay
#    * jstandard.DBC.InternationalTickHistory.enable
#
# Details regarding each of these properties may be found below.
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# LIBRARY PATH SETTING
# -----------------------------------------------------------------------------
# The path can be a colon separated list of directories to look for libraries.
# This value will be a system property called "jna.library.path" that is used by 
# the JNA framework.
# 
# (LINUX) You may choose to store the linked libraries under /usr/lib64 or /lib64
# since JNA looks there if it can't find them in the directory with the application.
# jna.library.path=/home/client/application/bin

jna.library.path=..//..//bin

# -----------------------------------------------------------------------------
# APPLICATION NAME SETTING
# -----------------------------------------------------------------------------
# The Application name can have up to a maximum of 13 characters
# note: The application name **must** start with the grave accent ( ` )

jstandard.DBC.program=`JSTN1_31_1_1

# -----------------------------------------------------------------------------
# CONNECTIONS:  Manual Reconnect Option
# -----------------------------------------------------------------------------
# This option enables the application to manage the reconnection logic in the 
# event that a connection to the IDC network is disrupted.  
#
# Valid values include: true and false, the default is false

#jstandard.DBC.manualConnect=false

# Unless there is a reason to manage the reconnection logic, programs should 
# allow the API to manage reconnecting to services in the event of a connection 
# disruption.
#
# note:  While the API will perform the necessary steps to reconnect to disrupted
#        services, the API will not resubscribe to instruments being watched. 
#        The application must request the data again once the connection is 
#        re-established.

# -----------------------------------------------------------------------------
# CONNECTIONS:  Connection Timeout Override Option
# -----------------------------------------------------------------------------
# The API allows up to 30 seconds to establish a connection before timing out  
# and making another attempt.  This default timeout value can be overridden in 
# two ways:
#
#    1.  Using the properties file jstandard.DBC.timeouts.connection property
#
#    2.  Specifying a value with the ConnectionSettings object passed into a
#        manager's connect() method
#
# ConnectionSettings Example:
#
#    connectionSettings.setConnectionTimeout(connectionTimeoutValue);
#
# note:  Timeout values are specified in milliseconds, and values set using 
#        setConnectionTimeout take precedence over values set using the properties 
#        file jstandard.DBC.timeouts.connection property.
# 
# Properties File Example:

#jstandard.DBC.timeouts.connection=30000

# note:  The above example sets the timeout value to 30 seconds, which is the
#        same as the default behavior.  Valid values are 1000 milliseconds and
#        above.

# Notes on Behavior:
#
# - If the timeout value is reached before the manager's connect() method establishes
#   a connection a ConnectionException will be thrown with one of the following error
#   status codes:
#
#      * DbcCodes.DBCAPI_ERROR.INVALIDNAME
#        An incorrect host name or IP address was supplied
#
#      * DbcCodes.DBCAPI_ERROR.WINSOCK
#        The TCP Socket could not be established. Ensure the network or IP address is
#        available and that your network permits access to it.
#
#      * DbcCodes.DBCAPI_ERROR.SERVER_NOT_AVAILABLE
#        There are no available servers to accept the connection requests.
#
# - If a value is set less than 1000 (1 second), a ConnectionException will be thrown
#   with an error status code of DbcCodes.DBCAPI_ERROR.INVALID_PARAM.
#
# - Use of the jstandard.DBC.timeouts.connection property and the 
#   ConnectionSettings.setConnectionTimeout() method is optional.  
#   The default timeout connection value is 30000 milliseconds (30 seconds).
#
# - Timeout values set by the ConnectionSettings.setConnectionTimeout method affect
#   ALL connections (regardless of manager type) made after the value is set.  
#   Connections existing prior to this value being set will use this value if they
#   lose connectivity and experience a reconnection.

# -----------------------------------------------------------------------------
# CONNECTIONS:  TCP NODELAY Option
# -----------------------------------------------------------------------------
# The standard buffering algorithm that governs TCP socket connections can be
# overridden for outbound traffic from the client using the API.  Typically, 
# it is not necessary or to override this setting, but some high-frequency 
# request applications may choose to do so to help improve performance and
# reduce latency.
#
# Valid values for this property are true and false.  True indicates to
# override the standard TCP buffering algorithm for outbound traffic; false
# does not override the standard algorithm.  The default setting is false.
#
# note: This setting affects all connections.

# jstandard.DBC.tcp.nodelay=false
