// <auto-generated />
using Atlas.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Atlas.Web.Data.Migrations
{
    [DbContext(typeof(AtlasDbContext))]
    partial class AtlasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Atlas.Web.Data.Entities.DeskEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Desks", (string)null);
                });

            modelBuilder.Entity("Atlas.Web.Data.Entities.DeskMemberEntity", b =>
                {
                    b.Property<string>("DeskKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.HasKey("DeskKey", "Email");

                    b.ToTable("DeskMembers", (string)null);
                });

            modelBuilder.Entity("Atlas.Web.Data.Entities.DeskMemberEntity", b =>
                {
                    b.HasOne("Atlas.Web.Data.Entities.DeskEntity", "Desk")
                        .WithMany("Members")
                        .HasForeignKey("DeskKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Desk");
                });

            modelBuilder.Entity("Atlas.Web.Data.Entities.DeskEntity", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
