/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as NatgasRouteImport } from './natgas'
import { Route as ForbiddenRouteImport } from './forbidden'
import { Route as AdminRouteImport } from './admin'
import { Route as AboutRouteImport } from './about'
import { Route as TradesRouteRouteImport } from './trades/route'
import { Route as IndexRouteImport } from './index'
import { Route as TradesTradeIdRouteRouteImport } from './trades/$tradeId/route'

const NatgasRoute = NatgasRouteImport.update({
  id: '/natgas',
  path: '/natgas',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesRouteRoute = TradesRouteRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesTradeIdRouteRoute = TradesTradeIdRouteRouteImport.update({
  id: '/$tradeId',
  path: '/$tradeId',
  getParentRoute: () => TradesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/trades': typeof TradesRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/forbidden': typeof ForbiddenRoute
  '/natgas': typeof NatgasRoute
  '/trades/$tradeId': typeof TradesTradeIdRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/trades': typeof TradesRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/forbidden': typeof ForbiddenRoute
  '/natgas': typeof NatgasRoute
  '/trades/$tradeId': typeof TradesTradeIdRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/trades': typeof TradesRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/forbidden': typeof ForbiddenRoute
  '/natgas': typeof NatgasRoute
  '/trades/$tradeId': typeof TradesTradeIdRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/trades'
    | '/about'
    | '/admin'
    | '/forbidden'
    | '/natgas'
    | '/trades/$tradeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/trades'
    | '/about'
    | '/admin'
    | '/forbidden'
    | '/natgas'
    | '/trades/$tradeId'
  id:
    | '__root__'
    | '/'
    | '/trades'
    | '/about'
    | '/admin'
    | '/forbidden'
    | '/natgas'
    | '/trades/$tradeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TradesRouteRoute: typeof TradesRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ForbiddenRoute: typeof ForbiddenRoute
  NatgasRoute: typeof NatgasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/natgas': {
      id: '/natgas'
      path: '/natgas'
      fullPath: '/natgas'
      preLoaderRoute: typeof NatgasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades': {
      id: '/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof TradesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades/$tradeId': {
      id: '/trades/$tradeId'
      path: '/$tradeId'
      fullPath: '/trades/$tradeId'
      preLoaderRoute: typeof TradesTradeIdRouteRouteImport
      parentRoute: typeof TradesRouteRoute
    }
  }
}

interface TradesRouteRouteChildren {
  TradesTradeIdRouteRoute: typeof TradesTradeIdRouteRoute
}

const TradesRouteRouteChildren: TradesRouteRouteChildren = {
  TradesTradeIdRouteRoute: TradesTradeIdRouteRoute,
}

const TradesRouteRouteWithChildren = TradesRouteRoute._addFileChildren(
  TradesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TradesRouteRoute: TradesRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ForbiddenRoute: ForbiddenRoute,
  NatgasRoute: NatgasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
