/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as TtfTimeSpreadRouteImport } from './ttf-time-spread'
import { Route as NbpRouteImport } from './nbp'
import { Route as NatgasRouteImport } from './natgas'
import { Route as ForbiddenRouteImport } from './forbidden'
import { Route as DesksRouteImport } from './desks'
import { Route as AdminRouteImport } from './admin'
import { Route as AboutRouteImport } from './about'
import { Route as TradesRouteRouteImport } from './trades/route'
import { Route as IndexRouteImport } from './index'
import { Route as DesksIndexRouteImport } from './desks.index'
import { Route as DesksKeyRouteImport } from './desks.$key'
import { Route as CoalSpreadsRouteImport } from './coal.spreads'
import { Route as CoalNewcastleRouteImport } from './coal.newcastle'
import { Route as CoalApi2RouteImport } from './coal.api2'
import { Route as TradesTradeIdRouteRouteImport } from './trades/$tradeId/route'

const TtfTimeSpreadRoute = TtfTimeSpreadRouteImport.update({
  id: '/ttf-time-spread',
  path: '/ttf-time-spread',
  getParentRoute: () => rootRouteImport,
} as any)
const NbpRoute = NbpRouteImport.update({
  id: '/nbp',
  path: '/nbp',
  getParentRoute: () => rootRouteImport,
} as any)
const NatgasRoute = NatgasRouteImport.update({
  id: '/natgas',
  path: '/natgas',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const DesksRoute = DesksRouteImport.update({
  id: '/desks',
  path: '/desks',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesRouteRoute = TradesRouteRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesksIndexRoute = DesksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DesksRoute,
} as any)
const DesksKeyRoute = DesksKeyRouteImport.update({
  id: '/$key',
  path: '/$key',
  getParentRoute: () => DesksRoute,
} as any)
const CoalSpreadsRoute = CoalSpreadsRouteImport.update({
  id: '/coal/spreads',
  path: '/coal/spreads',
  getParentRoute: () => rootRouteImport,
} as any)
const CoalNewcastleRoute = CoalNewcastleRouteImport.update({
  id: '/coal/newcastle',
  path: '/coal/newcastle',
  getParentRoute: () => rootRouteImport,
} as any)
const CoalApi2Route = CoalApi2RouteImport.update({
  id: '/coal/api2',
  path: '/coal/api2',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesTradeIdRouteRoute = TradesTradeIdRouteRouteImport.update({
  id: '/$tradeId',
  path: '/$tradeId',
  getParentRoute: () => TradesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/trades': typeof TradesRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/desks': typeof DesksRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/natgas': typeof NatgasRoute
  '/nbp': typeof NbpRoute
  '/ttf-time-spread': typeof TtfTimeSpreadRoute
  '/trades/$tradeId': typeof TradesTradeIdRouteRoute
  '/coal/api2': typeof CoalApi2Route
  '/coal/newcastle': typeof CoalNewcastleRoute
  '/coal/spreads': typeof CoalSpreadsRoute
  '/desks/$key': typeof DesksKeyRoute
  '/desks/': typeof DesksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/trades': typeof TradesRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/forbidden': typeof ForbiddenRoute
  '/natgas': typeof NatgasRoute
  '/nbp': typeof NbpRoute
  '/ttf-time-spread': typeof TtfTimeSpreadRoute
  '/trades/$tradeId': typeof TradesTradeIdRouteRoute
  '/coal/api2': typeof CoalApi2Route
  '/coal/newcastle': typeof CoalNewcastleRoute
  '/coal/spreads': typeof CoalSpreadsRoute
  '/desks/$key': typeof DesksKeyRoute
  '/desks': typeof DesksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/trades': typeof TradesRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/desks': typeof DesksRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/natgas': typeof NatgasRoute
  '/nbp': typeof NbpRoute
  '/ttf-time-spread': typeof TtfTimeSpreadRoute
  '/trades/$tradeId': typeof TradesTradeIdRouteRoute
  '/coal/api2': typeof CoalApi2Route
  '/coal/newcastle': typeof CoalNewcastleRoute
  '/coal/spreads': typeof CoalSpreadsRoute
  '/desks/$key': typeof DesksKeyRoute
  '/desks/': typeof DesksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/trades'
    | '/about'
    | '/admin'
    | '/desks'
    | '/forbidden'
    | '/natgas'
    | '/nbp'
    | '/ttf-time-spread'
    | '/trades/$tradeId'
    | '/coal/api2'
    | '/coal/newcastle'
    | '/coal/spreads'
    | '/desks/$key'
    | '/desks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/trades'
    | '/about'
    | '/admin'
    | '/forbidden'
    | '/natgas'
    | '/nbp'
    | '/ttf-time-spread'
    | '/trades/$tradeId'
    | '/coal/api2'
    | '/coal/newcastle'
    | '/coal/spreads'
    | '/desks/$key'
    | '/desks'
  id:
    | '__root__'
    | '/'
    | '/trades'
    | '/about'
    | '/admin'
    | '/desks'
    | '/forbidden'
    | '/natgas'
    | '/nbp'
    | '/ttf-time-spread'
    | '/trades/$tradeId'
    | '/coal/api2'
    | '/coal/newcastle'
    | '/coal/spreads'
    | '/desks/$key'
    | '/desks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TradesRouteRoute: typeof TradesRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  DesksRoute: typeof DesksRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
  NatgasRoute: typeof NatgasRoute
  NbpRoute: typeof NbpRoute
  TtfTimeSpreadRoute: typeof TtfTimeSpreadRoute
  CoalApi2Route: typeof CoalApi2Route
  CoalNewcastleRoute: typeof CoalNewcastleRoute
  CoalSpreadsRoute: typeof CoalSpreadsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ttf-time-spread': {
      id: '/ttf-time-spread'
      path: '/ttf-time-spread'
      fullPath: '/ttf-time-spread'
      preLoaderRoute: typeof TtfTimeSpreadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nbp': {
      id: '/nbp'
      path: '/nbp'
      fullPath: '/nbp'
      preLoaderRoute: typeof NbpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/natgas': {
      id: '/natgas'
      path: '/natgas'
      fullPath: '/natgas'
      preLoaderRoute: typeof NatgasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desks': {
      id: '/desks'
      path: '/desks'
      fullPath: '/desks'
      preLoaderRoute: typeof DesksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades': {
      id: '/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof TradesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desks/': {
      id: '/desks/'
      path: '/'
      fullPath: '/desks/'
      preLoaderRoute: typeof DesksIndexRouteImport
      parentRoute: typeof DesksRoute
    }
    '/desks/$key': {
      id: '/desks/$key'
      path: '/$key'
      fullPath: '/desks/$key'
      preLoaderRoute: typeof DesksKeyRouteImport
      parentRoute: typeof DesksRoute
    }
    '/coal/spreads': {
      id: '/coal/spreads'
      path: '/coal/spreads'
      fullPath: '/coal/spreads'
      preLoaderRoute: typeof CoalSpreadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coal/newcastle': {
      id: '/coal/newcastle'
      path: '/coal/newcastle'
      fullPath: '/coal/newcastle'
      preLoaderRoute: typeof CoalNewcastleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coal/api2': {
      id: '/coal/api2'
      path: '/coal/api2'
      fullPath: '/coal/api2'
      preLoaderRoute: typeof CoalApi2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades/$tradeId': {
      id: '/trades/$tradeId'
      path: '/$tradeId'
      fullPath: '/trades/$tradeId'
      preLoaderRoute: typeof TradesTradeIdRouteRouteImport
      parentRoute: typeof TradesRouteRoute
    }
  }
}

interface TradesRouteRouteChildren {
  TradesTradeIdRouteRoute: typeof TradesTradeIdRouteRoute
}

const TradesRouteRouteChildren: TradesRouteRouteChildren = {
  TradesTradeIdRouteRoute: TradesTradeIdRouteRoute,
}

const TradesRouteRouteWithChildren = TradesRouteRoute._addFileChildren(
  TradesRouteRouteChildren,
)

interface DesksRouteChildren {
  DesksKeyRoute: typeof DesksKeyRoute
  DesksIndexRoute: typeof DesksIndexRoute
}

const DesksRouteChildren: DesksRouteChildren = {
  DesksKeyRoute: DesksKeyRoute,
  DesksIndexRoute: DesksIndexRoute,
}

const DesksRouteWithChildren = DesksRoute._addFileChildren(DesksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TradesRouteRoute: TradesRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  DesksRoute: DesksRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
  NatgasRoute: NatgasRoute,
  NbpRoute: NbpRoute,
  TtfTimeSpreadRoute: TtfTimeSpreadRoute,
  CoalApi2Route: CoalApi2Route,
  CoalNewcastleRoute: CoalNewcastleRoute,
  CoalSpreadsRoute: CoalSpreadsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
